/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BuyTicketRequest {
  bankPassword: string;
  eventId: number;
  numberAccount: string;
}
