/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ReviewDto {
  content?: string;
  degree?: number;
  eventName?: string;
  reviewer?: string;
}
