/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  accountNumber?: string;
  accountStatus?: string;
  birthDate?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  phoneNumber?: string;
  role?: 'USER' | 'ADMIN';
  userId?: number;
  username?: string;
}
