/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeatherDto } from '../../models/weather-dto';

export interface GetWeatherOnEventDay$Params {
  eventId: number;
}

export function getWeatherOnEventDay(http: HttpClient, rootUrl: string, params: {
  eventId: number | undefined
}, context?: HttpContext | undefined): Observable<StrictHttpResponse<WeatherDto>> {
  const rb = new RequestBuilder(rootUrl, getWeatherOnEventDay.PATH, 'get');
  if (params) {
    rb.query('eventId', params.eventId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WeatherDto>;
    })
  );
}

getWeatherOnEventDay.PATH = '/api/weather';
