/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeleteEventResponse } from '../../models/delete-event-response';

export interface DeleteEvent$Params {
  eventId: number;
  Authorization?: string;
}

export function deleteEvent(http: HttpClient, rootUrl: string, params: {
  eventId: number | undefined
}, context?: HttpContext | undefined): Observable<StrictHttpResponse<DeleteEventResponse>> {
  const rb = new RequestBuilder(rootUrl, deleteEvent.PATH, 'delete');
  if (params) {
    rb.query('eventId', params.eventId, {});
    rb.header('Authorization', params, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DeleteEventResponse>;
    })
  );
}

deleteEvent.PATH = '/api/events';
