/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventDto } from '../../models/event-dto';

export interface GetEventByName$Params {
  eventName: string;
}

export function getEventByName(http: HttpClient, rootUrl: string, params: string, context?: HttpContext | undefined): Observable<StrictHttpResponse<EventDto>> {
  const rb = new RequestBuilder(rootUrl, getEventByName.PATH, 'get');
  if (params) {
    rb.query('eventName', params, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EventDto>;
    })
  );
}

getEventByName.PATH = '/api/events/eventName';
