/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { uploadEvents1 } from '../fn/csv-controller/upload-events-1';
import { UploadEvents1$Params } from '../fn/csv-controller/upload-events-1';
import { uploadUsers } from '../fn/csv-controller/upload-users';
import { UploadUsers$Params } from '../fn/csv-controller/upload-users';

@Injectable({ providedIn: 'root' })
export class CsvControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `uploadUsers()` */
  static readonly UploadUsersPath = '/api/csv/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadUsers()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadUsers$Response(params?: UploadUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return uploadUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadUsers$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadUsers(params?: UploadUsers$Params, context?: HttpContext): Observable<number> {
    return this.uploadUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `uploadEvents1()` */
  static readonly UploadEvents1Path = '/api/csv/events';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadEvents1()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadEvents1$Response(params?: UploadEvents1$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return uploadEvents1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadEvents1$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadEvents1(params?: UploadEvents1$Params, context?: HttpContext): Observable<string> {
    return this.uploadEvents1$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
