/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getWeatherOnEventDay } from '../fn/weather-controller/get-weather-on-event-day';
import { GetWeatherOnEventDay$Params } from '../fn/weather-controller/get-weather-on-event-day';
import { WeatherDto } from '../models/weather-dto';

@Injectable({ providedIn: 'root' })
export class WeatherControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getWeatherOnEventDay()` */
  static readonly GetWeatherOnEventDayPath = '/api/weather';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWeatherOnEventDay()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWeatherOnEventDay$Response(params: {
    eventId: number | undefined
  }, context?: HttpContext | undefined): Observable<StrictHttpResponse<WeatherDto>> {
    return getWeatherOnEventDay(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWeatherOnEventDay$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWeatherOnEventDay(params: { eventId: number | undefined }, context?: HttpContext): Observable<WeatherDto> {
    return this.getWeatherOnEventDay$Response(params, context).pipe(
      map((r: StrictHttpResponse<WeatherDto>): WeatherDto => r.body)
    );
  }

}
